#pragma once

#include "poole/core.h"

namespace Poole
{
	enum class ECursorClamping : u8
	{
		None,
		Clamp,
		LastValidPosition,
	};

	enum class ECursorNormalization : u8
	{
		Absolute = 0,
		ZeroToOne = 1,
		NegativeOneToOne = 2,

		FLAG_Aspect = 4, //Scaled for aspect ratio
		FLAG_Camera = 8, //Move relative to camera
		ALL_FLAGS = FLAG_Aspect | FLAG_Camera,

		ZeroToOneAspect = ZeroToOne | FLAG_Aspect,
		NegativeOneToOneAspect = NegativeOneToOne | FLAG_Aspect,
		CameraNegativeOneToOneAspect = NegativeOneToOne | FLAG_Aspect | FLAG_Camera,
	};
	ENUM_FLAGS(ECursorNormalization)

	enum class EInputPress : u8
	{
		//The key or mouse button was released.
		RELEASE = 0,
		//The key or mouse button was pressed.
		PRESS = 1,
		//The key was held down until it repeated.
		REPEAT = 2,
	};

	enum class EInputKeyMod : u8
	{
		//If this bit is set one or more Shift keys were held down.
		SHIFT            = 0x0001,
		//If this bit is set one or more Control keys were held down.
		CONTROL          = 0x0002,
		//If this bit is set one or more Alt keys were held down.
		ALT              = 0x0004,
		//If this bit is set one or more Super keys were held down.
		SUPER            = 0x0008,
		//If this bit is set the Caps Lock key is enabled and the @ref
		//GLFW_LOCK_KEY_MODS input mode is set.
		CAPS_LOCK        = 0x0010,
		//If this bit is set the Num Lock key is enabledand the @ref
		//GLFW_LOCK_KEY_MODS input mode is set.
		NUM_LOCK         = 0x0020,
	};
	ENUM_FLAGS(EInputKeyMod)

	enum class EJoystickID : u8
	{
		NONE = 0,
		JOYSTICK_1    = 1, //WARNING GLFW3 uses JOYSTICK_1 == 0
		JOYSTICK_2    = 2,
		JOYSTICK_3    = 3,
		JOYSTICK_4    = 4,
		JOYSTICK_5    = 5,
		JOYSTICK_6    = 6,
		JOYSTICK_7    = 7,
		JOYSTICK_8    = 8,
		//JOYSTICK_9    = 9,
		//JOYSTICK_10   = 10,
		//JOYSTICK_11   = 11,
		//JOYSTICK_12   = 12,
		//JOYSTICK_13   = 13,
		//JOYSTICK_14   = 14,
		//JOYSTICK_15   = 15,
		//JOYSTICK_16   = 16,
		JOYSTICK_LAST = JOYSTICK_8, //NOTE: NOT 16!!
	};

	enum class EInputAxis : u8
	{
		NONE						= 0,

		/* Mouse Axes */
		MOUSE_POSITION_X			= 1,
		MOUSE_POSITION_Y			= 2,
		MOUSE_DELTA_X				= 3,
		MOUSE_DELTA_Y				= 4,
		MOUSE_SCROLL_DELTA_X		= 5,
		MOUSE_SCROLL_DELTA_Y		= 6,
		MOUSE_FIRST					= MOUSE_POSITION_X,
		MOUSE_LAST					= MOUSE_SCROLL_DELTA_Y,

		/* Gamepad Axes 'Flags' */
		GAMEPAD_AXIS_FLAGS			= 0b0000'1111,
		GAMEPAD_AXIS_LEFT_X         = 1,          //Previously 0 in GLFW
		GAMEPAD_AXIS_LEFT_Y         = 2,
		GAMEPAD_AXIS_RIGHT_X        = 3,
		GAMEPAD_AXIS_RIGHT_Y        = 4,
		GAMEPAD_AXIS_LEFT_TRIGGER   = 5,
		GAMEPAD_AXIS_RIGHT_TRIGGER  = 6,
		GAMEPAD_AXIS_FIRST          = GAMEPAD_AXIS_LEFT_X,
		GAMEPAD_AXIS_LAST           = GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks Flags */
		IS_JOYSTICK_FLAG = 0b1111'0000,
		JOYSTICK_FLAG_1  = 0b0001'0000, //Previously 0
		JOYSTICK_FLAG_2  = 0b0010'0000, //Previously 1
		JOYSTICK_FLAG_3  = 0b0011'0000, //Previously 2
		JOYSTICK_FLAG_4  = 0b0100'0000, //Previously 3
		JOYSTICK_FLAG_5  = 0b0101'0000, //Previously 4
		JOYSTICK_FLAG_6  = 0b0110'0000, //Previously 5
		JOYSTICK_FLAG_7  = 0b0111'0000, //Previously 6
		JOYSTICK_FLAG_8  = 0b1000'0000, //Previously 7
		//JOYSTICK_FLAG_9  = 0b1001'0000, //Previously 8
		//JOYSTICK_FLAG_10 = 0b1010'0000, //Previously 9
		//JOYSTICK_FLAG_11 = 0b1011'0000, //Previously 10
		//JOYSTICK_FLAG_12 = 0b1100'0000, //Previously 11
		//JOYSTICK_FLAG_13 = 0b1101'0000, //Previously 12
		//JOYSTICK_FLAG_14 = 0b1110'0000, //Previously 13
		//JOYSTICK_FLAG_15 = 0b1111'0000, //Previously 14
		//JOYSTICK_FLAG_16 = IMPOSSIBLE,  //Previously 15

		/* Joysticks / Gamepad 1 Axes */
		G1_LEFT_X		  = JOYSTICK_FLAG_1 | GAMEPAD_AXIS_LEFT_X,
		G1_LEFT_Y         = JOYSTICK_FLAG_1 | GAMEPAD_AXIS_LEFT_Y,
		G1_RIGHT_X        = JOYSTICK_FLAG_1 | GAMEPAD_AXIS_RIGHT_X,
		G1_RIGHT_Y        = JOYSTICK_FLAG_1 | GAMEPAD_AXIS_RIGHT_Y,
		G1_LEFT_TRIGGER   = JOYSTICK_FLAG_1 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G1_RIGHT_TRIGGER  = JOYSTICK_FLAG_1 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 2 Axes */
		G2_LEFT_X		  = JOYSTICK_FLAG_2 | GAMEPAD_AXIS_LEFT_X,
		G2_LEFT_Y         = JOYSTICK_FLAG_2 | GAMEPAD_AXIS_LEFT_Y,
		G2_RIGHT_X        = JOYSTICK_FLAG_2 | GAMEPAD_AXIS_RIGHT_X,
		G2_RIGHT_Y        = JOYSTICK_FLAG_2 | GAMEPAD_AXIS_RIGHT_Y,
		G2_LEFT_TRIGGER   = JOYSTICK_FLAG_2 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G2_RIGHT_TRIGGER  = JOYSTICK_FLAG_2 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 3 Axes */
		G3_LEFT_X		  = JOYSTICK_FLAG_3 | GAMEPAD_AXIS_LEFT_X,
		G3_LEFT_Y         = JOYSTICK_FLAG_3 | GAMEPAD_AXIS_LEFT_Y,
		G3_RIGHT_X        = JOYSTICK_FLAG_3 | GAMEPAD_AXIS_RIGHT_X,
		G3_RIGHT_Y        = JOYSTICK_FLAG_3 | GAMEPAD_AXIS_RIGHT_Y,
		G3_LEFT_TRIGGER   = JOYSTICK_FLAG_3 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G3_RIGHT_TRIGGER  = JOYSTICK_FLAG_3 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 4 Axes */
		G4_LEFT_X		  = JOYSTICK_FLAG_4 | GAMEPAD_AXIS_LEFT_X,
		G4_LEFT_Y         = JOYSTICK_FLAG_4 | GAMEPAD_AXIS_LEFT_Y,
		G4_RIGHT_X        = JOYSTICK_FLAG_4 | GAMEPAD_AXIS_RIGHT_X,
		G4_RIGHT_Y        = JOYSTICK_FLAG_4 | GAMEPAD_AXIS_RIGHT_Y,
		G4_LEFT_TRIGGER   = JOYSTICK_FLAG_4 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G4_RIGHT_TRIGGER  = JOYSTICK_FLAG_4 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 5 Axes */
		G5_LEFT_X		  = JOYSTICK_FLAG_5 | GAMEPAD_AXIS_LEFT_X,
		G5_LEFT_Y         = JOYSTICK_FLAG_5 | GAMEPAD_AXIS_LEFT_Y,
		G5_RIGHT_X        = JOYSTICK_FLAG_5 | GAMEPAD_AXIS_RIGHT_X,
		G5_RIGHT_Y        = JOYSTICK_FLAG_5 | GAMEPAD_AXIS_RIGHT_Y,
		G5_LEFT_TRIGGER   = JOYSTICK_FLAG_5 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G5_RIGHT_TRIGGER  = JOYSTICK_FLAG_5 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 6 Axes */
		G6_LEFT_X		  = JOYSTICK_FLAG_6 | GAMEPAD_AXIS_LEFT_X,
		G6_LEFT_Y         = JOYSTICK_FLAG_6 | GAMEPAD_AXIS_LEFT_Y,
		G6_RIGHT_X        = JOYSTICK_FLAG_6 | GAMEPAD_AXIS_RIGHT_X,
		G6_RIGHT_Y        = JOYSTICK_FLAG_6 | GAMEPAD_AXIS_RIGHT_Y,
		G6_LEFT_TRIGGER   = JOYSTICK_FLAG_6 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G6_RIGHT_TRIGGER  = JOYSTICK_FLAG_6 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 7 Axes */
		G7_LEFT_X		  = JOYSTICK_FLAG_7 | GAMEPAD_AXIS_LEFT_X,
		G7_LEFT_Y         = JOYSTICK_FLAG_7 | GAMEPAD_AXIS_LEFT_Y,
		G7_RIGHT_X        = JOYSTICK_FLAG_7 | GAMEPAD_AXIS_RIGHT_X,
		G7_RIGHT_Y        = JOYSTICK_FLAG_7 | GAMEPAD_AXIS_RIGHT_Y,
		G7_LEFT_TRIGGER   = JOYSTICK_FLAG_7 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G7_RIGHT_TRIGGER  = JOYSTICK_FLAG_7 | GAMEPAD_AXIS_RIGHT_TRIGGER,

		/* Joysticks / Gamepad 8 Axes */
		G8_LEFT_X		  = JOYSTICK_FLAG_8 | GAMEPAD_AXIS_LEFT_X,
		G8_LEFT_Y         = JOYSTICK_FLAG_8 | GAMEPAD_AXIS_LEFT_Y,
		G8_RIGHT_X        = JOYSTICK_FLAG_8 | GAMEPAD_AXIS_RIGHT_X,
		G8_RIGHT_Y        = JOYSTICK_FLAG_8 | GAMEPAD_AXIS_RIGHT_Y,
		G8_LEFT_TRIGGER   = JOYSTICK_FLAG_8 | GAMEPAD_AXIS_LEFT_TRIGGER,
		G8_RIGHT_TRIGGER  = JOYSTICK_FLAG_8 | GAMEPAD_AXIS_RIGHT_TRIGGER,
	};
	ENUM_FLAGS(EInputAxis)

	enum class EInputButton : u16
	{
		NONE = 0,

		/* Printable keys */
		KEY_SPACE               = 32,
		KEY_APOSTROPHE          = 39  /* ' */,
		KEY_COMMA               = 44  /* , */,
		KEY_MINUS               = 45  /* - */,
		KEY_PERIOD              = 46  /* . */,
		KEY_SLASH               = 47  /* / */,
		KEY_0                   = 48,
		KEY_1                   = 49,
		KEY_2                   = 50,
		KEY_3                   = 51,
		KEY_4                   = 52,
		KEY_5                   = 53,
		KEY_6                   = 54,
		KEY_7                   = 55,
		KEY_8                   = 56,
		KEY_9                   = 57,
		KEY_SEMICOLON           = 59  /* ; */,
		KEY_EQUAL               = 61  /* = */,
		KEY_A                   = 65,
		KEY_B                   = 66,
		KEY_C                   = 67,
		KEY_D                   = 68,
		KEY_E                   = 69,
		KEY_F                   = 70,
		KEY_G                   = 71,
		KEY_H                   = 72,
		KEY_I                   = 73,
		KEY_J                   = 74,
		KEY_K                   = 75,
		KEY_L                   = 76,
		KEY_M                   = 77,
		KEY_N                   = 78,
		KEY_O                   = 79,
		KEY_P                   = 80,
		KEY_Q                   = 81,
		KEY_R                   = 82,
		KEY_S                   = 83,
		KEY_T                   = 84,
		KEY_U                   = 85,
		KEY_V                   = 86,
		KEY_W                   = 87,
		KEY_X                   = 88,
		KEY_Y                   = 89,
		KEY_Z                   = 90,
		KEY_LEFT_BRACKET        = 91  /* [ */,
		KEY_BACKSLASH           = 92  /* \ */,
		KEY_RIGHT_BRACKET       = 93  /* ] */,
		KEY_GRAVE_ACCENT        = 96  /* ` */,
		KEY_WORLD_1             = 161 /* non-US #1 */,
		KEY_WORLD_2             = 162 /* non-US #2 */,
		KEY_FIRST_PRINTABLE		= KEY_SPACE,
		KEY_LAST_PRINTABLE	    = KEY_WORLD_2,

		/* Function keys */
		KEY_ESCAPE              = 256,
		KEY_ENTER               = 257,
		KEY_TAB                 = 258,
		KEY_BACKSPACE           = 259,
		KEY_INSERT              = 260,
		KEY_DELETE              = 261,
		KEY_RIGHT               = 262,
		KEY_LEFT                = 263,
		KEY_DOWN                = 264,
		KEY_UP                  = 265,
		KEY_PAGE_UP             = 266,
		KEY_PAGE_DOWN           = 267,
		KEY_HOME                = 268,
		KEY_END                 = 269,
		KEY_CAPS_LOCK           = 280,
		KEY_SCROLL_LOCK         = 281,
		KEY_NUM_LOCK            = 282,
		KEY_PRINT_SCREEN        = 283,
		KEY_PAUSE               = 284,
		KEY_F1                  = 290,
		KEY_F2                  = 291,
		KEY_F3                  = 292,
		KEY_F4                  = 293,
		KEY_F5                  = 294,
		KEY_F6                  = 295,
		KEY_F7                  = 296,
		KEY_F8                  = 297,
		KEY_F9                  = 298,
		KEY_F10                 = 299,
		KEY_F11                 = 300,
		KEY_F12                 = 301,
		KEY_F13                 = 302,
		KEY_F14                 = 303,
		KEY_F15                 = 304,
		KEY_F16                 = 305,
		KEY_F17                 = 306,
		KEY_F18                 = 307,
		KEY_F19                 = 308,
		KEY_F20                 = 309,
		KEY_F21                 = 310,
		KEY_F22                 = 311,
		KEY_F23                 = 312,
		KEY_F24                 = 313,
		KEY_F25                 = 314,
		KEY_KP_0                = 320,
		KEY_KP_1                = 321,
		KEY_KP_2                = 322,
		KEY_KP_3                = 323,
		KEY_KP_4                = 324,
		KEY_KP_5                = 325,
		KEY_KP_6                = 326,
		KEY_KP_7                = 327,
		KEY_KP_8                = 328,
		KEY_KP_9                = 329,
		KEY_KP_DECIMAL          = 330,
		KEY_KP_DIVIDE           = 331,
		KEY_KP_MULTIPLY         = 332,
		KEY_KP_SUBTRACT         = 333,
		KEY_KP_ADD              = 334,
		KEY_KP_ENTER            = 335,
		KEY_KP_EQUAL            = 336,
		KEY_LEFT_SHIFT          = 340,
		KEY_LEFT_CONTROL        = 341,
		KEY_LEFT_ALT            = 342,
		KEY_LEFT_SUPER          = 343,
		KEY_RIGHT_SHIFT         = 344,
		KEY_RIGHT_CONTROL       = 345,
		KEY_RIGHT_ALT           = 346,
		KEY_RIGHT_SUPER         = 347,
		KEY_MENU                = 348,
		KEY_FIRST_FUNCTIONAL	= KEY_ESCAPE,
		KEY_LAST_FUNCTIONAL     = KEY_MENU,

		/* Mouse Buttons */
		MOUSE_BUTTON_OFFSET     = KEY_LAST_FUNCTIONAL + 1,
		MOUSE_BUTTON_1          = MOUSE_BUTTON_OFFSET + 0,
		MOUSE_BUTTON_2          = MOUSE_BUTTON_OFFSET + 1,
		MOUSE_BUTTON_3          = MOUSE_BUTTON_OFFSET + 2,
		MOUSE_BUTTON_4          = MOUSE_BUTTON_OFFSET + 3,
		MOUSE_BUTTON_5          = MOUSE_BUTTON_OFFSET + 4,
		MOUSE_BUTTON_6          = MOUSE_BUTTON_OFFSET + 5,
		MOUSE_BUTTON_7          = MOUSE_BUTTON_OFFSET + 6,
		MOUSE_BUTTON_8          = MOUSE_BUTTON_OFFSET + 7,
		MOUSE_BUTTON_LEFT       = MOUSE_BUTTON_1,
		MOUSE_BUTTON_RIGHT      = MOUSE_BUTTON_2,
		MOUSE_BUTTON_MIDDLE     = MOUSE_BUTTON_3,
		MOUSE_BUTTON_FIRST		= MOUSE_BUTTON_1,
		MOUSE_BUTTON_LAST       = MOUSE_BUTTON_8, //356 == 0b0000_0001_0110_0100

		/* Joysticks Flags */
		IS_JOYSTICK_FLAG = 0b1111'0000'0000'0000,
		JOYSTICK_FLAG_1  = 0b0001'0000'0000'0000, //Previously 0
		JOYSTICK_FLAG_2  = 0b0010'0000'0000'0000, //Previously 1
		JOYSTICK_FLAG_3  = 0b0011'0000'0000'0000, //Previously 2
		JOYSTICK_FLAG_4  = 0b0100'0000'0000'0000, //Previously 3
		JOYSTICK_FLAG_5  = 0b0101'0000'0000'0000, //Previously 4
		JOYSTICK_FLAG_6  = 0b0110'0000'0000'0000, //Previously 5
		JOYSTICK_FLAG_7  = 0b0111'0000'0000'0000, //Previously 6
		JOYSTICK_FLAG_8  = 0b1000'0000'0000'0000, //Previously 7
		//JOYSTICK_FLAG_9  = 0b1001'0000'0000'0000, //Previously 8
		//JOYSTICK_FLAG_10 = 0b1010'0000'0000'0000, //Previously 9
		//JOYSTICK_FLAG_11 = 0b1011'0000'0000'0000, //Previously 10
		//JOYSTICK_FLAG_12 = 0b1100'0000'0000'0000, //Previously 11
		//JOYSTICK_FLAG_13 = 0b1101'0000'0000'0000, //Previously 12
		//JOYSTICK_FLAG_14 = 0b1110'0000'0000'0000, //Previously 13
		//JOYSTICK_FLAG_15 = 0b1111'0000'0000'0000, //Previously 14
		//JOYSTICK_FLAG_16 = IMPOSSIBLE,			//Previously 15  

		/* Joysticks Hat Flags */
		IS_JOYSTICK_HAT_FLAG		 = 0b0000'0000'0000'1111,
		JOYSTICK_HAT_FLAG_CENTERED   = 0,
		JOYSTICK_HAT_FLAG_UP         = 1,
		JOYSTICK_HAT_FLAG_RIGHT      = 2,
		JOYSTICK_HAT_FLAG_DOWN       = 4,
		JOYSTICK_HAT_FLAG_LEFT       = 8,
		JOYSTICK_HAT_FLAG_RIGHT_UP   = (JOYSTICK_HAT_FLAG_RIGHT | JOYSTICK_HAT_FLAG_UP),
		JOYSTICK_HAT_FLAG_RIGHT_DOWN = (JOYSTICK_HAT_FLAG_RIGHT | JOYSTICK_HAT_FLAG_DOWN),
		JOYSTICK_HAT_FLAG_LEFT_UP    = (JOYSTICK_HAT_FLAG_LEFT  | JOYSTICK_HAT_FLAG_UP),
		JOYSTICK_HAT_FLAG_LEFT_DOWN  = (JOYSTICK_HAT_FLAG_LEFT  | JOYSTICK_HAT_FLAG_DOWN),

		/* Joysticks(Gamepad) Button 'Flags' */
		GAMEPAD_BUTTON_FLAGS		 = 0b0000'0000'1111'0000,
		GAMEPAD_BUTTON_SHIFT         = 4,
		GAMEPAD_BUTTON_A             = 1  << GAMEPAD_BUTTON_SHIFT, //Previously 0 in GLFW
		GAMEPAD_BUTTON_B             = 2  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_X             = 3  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_Y             = 4  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_LEFT_BUMPER   = 5  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_RIGHT_BUMPER  = 6  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_BACK          = 7  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_START         = 8  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_GUIDE         = 9  << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_LEFT_THUMB    = 10 << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_RIGHT_THUMB   = 11 << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_DPAD_UP       = 12 << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_DPAD_RIGHT    = 13 << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_DPAD_DOWN     = 14 << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_DPAD_LEFT     = 15 << GAMEPAD_BUTTON_SHIFT,
		GAMEPAD_BUTTON_FIRST		 = GAMEPAD_BUTTON_A,
		GAMEPAD_BUTTON_LAST          = GAMEPAD_BUTTON_DPAD_LEFT,
		GAMEPAD_BUTTON_CROSS		 = GAMEPAD_BUTTON_A,
		GAMEPAD_BUTTON_CIRCLE		 = GAMEPAD_BUTTON_B,
		GAMEPAD_BUTTON_SQUARE		 = GAMEPAD_BUTTON_X,
		GAMEPAD_BUTTON_TRIANGLE		 = GAMEPAD_BUTTON_Y,

		/* Joysticks / Gamepad 1 Buttons */
		J1_HAT_CENTERED   = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_CENTERED,
		J1_HAT_UP         = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_UP,
		J1_HAT_RIGHT      = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_RIGHT,
		J1_HAT_DOWN       = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_DOWN,
		J1_HAT_LEFT       = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_LEFT,
		J1_HAT_RIGHT_UP   = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J1_HAT_RIGHT_DOWN = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J1_HAT_LEFT_UP    = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J1_HAT_LEFT_DOWN  = JOYSTICK_FLAG_1 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G1_A			  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_A,
		G1_B			  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_B,
		G1_X			  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_X,
		G1_Y			  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_Y,
		G1_LEFT_BUMPER	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G1_RIGHT_BUMPER	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G1_BACK			  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_BACK,
		G1_START		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_START,
		G1_GUIDE		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_GUIDE,
		G1_LEFT_THUMB	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_LEFT_THUMB,
		G1_RIGHT_THUMB	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G1_DPAD_UP		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_DPAD_UP,
		G1_DPAD_RIGHT	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G1_DPAD_DOWN	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_DPAD_DOWN,
		G1_DPAD_LEFT	  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_DPAD_LEFT,
		G1_LAST			  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_LAST,
		G1_CROSS		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_CROSS,
		G1_CIRCLE		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_CIRCLE,
		G1_SQUARE		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_SQUARE,
		G1_TRIANGLE		  = JOYSTICK_FLAG_1 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 2 Buttons */
		J2_HAT_CENTERED   = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_CENTERED,
		J2_HAT_UP         = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_UP,
		J2_HAT_RIGHT      = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_RIGHT,
		J2_HAT_DOWN       = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_DOWN,
		J2_HAT_LEFT       = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_LEFT,
		J2_HAT_RIGHT_UP   = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J2_HAT_RIGHT_DOWN = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J2_HAT_LEFT_UP    = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J2_HAT_LEFT_DOWN  = JOYSTICK_FLAG_2 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G2_A			  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_A,
		G2_B			  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_B,
		G2_X			  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_X,
		G2_Y			  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_Y,
		G2_LEFT_BUMPER	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G2_RIGHT_BUMPER	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G2_BACK			  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_BACK,
		G2_START		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_START,
		G2_GUIDE		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_GUIDE,
		G2_LEFT_THUMB	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_LEFT_THUMB,
		G2_RIGHT_THUMB	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G2_DPAD_UP		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_DPAD_UP,
		G2_DPAD_RIGHT	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G2_DPAD_DOWN	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_DPAD_DOWN,
		G2_DPAD_LEFT	  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_DPAD_LEFT,
		G2_LAST			  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_LAST,
		G2_CROSS		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_CROSS,
		G2_CIRCLE		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_CIRCLE,
		G2_SQUARE		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_SQUARE,
		G2_TRIANGLE		  = JOYSTICK_FLAG_2 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 3 Buttons */
		J3_HAT_CENTERED   = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_CENTERED,
		J3_HAT_UP         = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_UP,
		J3_HAT_RIGHT      = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_RIGHT,
		J3_HAT_DOWN       = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_DOWN,
		J3_HAT_LEFT       = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_LEFT,
		J3_HAT_RIGHT_UP   = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J3_HAT_RIGHT_DOWN = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J3_HAT_LEFT_UP    = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J3_HAT_LEFT_DOWN  = JOYSTICK_FLAG_3 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G3_A			  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_A,
		G3_B			  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_B,
		G3_X			  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_X,
		G3_Y			  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_Y,
		G3_LEFT_BUMPER	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G3_RIGHT_BUMPER	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G3_BACK			  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_BACK,
		G3_START		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_START,
		G3_GUIDE		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_GUIDE,
		G3_LEFT_THUMB	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_LEFT_THUMB,
		G3_RIGHT_THUMB	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G3_DPAD_UP		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_DPAD_UP,
		G3_DPAD_RIGHT	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G3_DPAD_DOWN	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_DPAD_DOWN,
		G3_DPAD_LEFT	  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_DPAD_LEFT,
		G3_LAST			  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_LAST,
		G3_CROSS		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_CROSS,
		G3_CIRCLE		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_CIRCLE,
		G3_SQUARE		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_SQUARE,
		G3_TRIANGLE		  = JOYSTICK_FLAG_3 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 4 Buttons */
		J4_HAT_CENTERED   = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_CENTERED,
		J4_HAT_UP         = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_UP,
		J4_HAT_RIGHT      = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_RIGHT,
		J4_HAT_DOWN       = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_DOWN,
		J4_HAT_LEFT       = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_LEFT,
		J4_HAT_RIGHT_UP   = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J4_HAT_RIGHT_DOWN = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J4_HAT_LEFT_UP    = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J4_HAT_LEFT_DOWN  = JOYSTICK_FLAG_4 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G4_A			  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_A,
		G4_B			  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_B,
		G4_X			  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_X,
		G4_Y			  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_Y,
		G4_LEFT_BUMPER	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G4_RIGHT_BUMPER	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G4_BACK			  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_BACK,
		G4_START		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_START,
		G4_GUIDE		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_GUIDE,
		G4_LEFT_THUMB	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_LEFT_THUMB,
		G4_RIGHT_THUMB	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G4_DPAD_UP		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_DPAD_UP,
		G4_DPAD_RIGHT	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G4_DPAD_DOWN	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_DPAD_DOWN,
		G4_DPAD_LEFT	  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_DPAD_LEFT,
		G4_LAST			  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_LAST,
		G4_CROSS		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_CROSS,
		G4_CIRCLE		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_CIRCLE,
		G4_SQUARE		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_SQUARE,
		G4_TRIANGLE		  = JOYSTICK_FLAG_4 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 5 Buttons */
		J5_HAT_CENTERED   = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_CENTERED,
		J5_HAT_UP         = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_UP,
		J5_HAT_RIGHT      = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_RIGHT,
		J5_HAT_DOWN       = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_DOWN,
		J5_HAT_LEFT       = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_LEFT,
		J5_HAT_RIGHT_UP   = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J5_HAT_RIGHT_DOWN = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J5_HAT_LEFT_UP    = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J5_HAT_LEFT_DOWN  = JOYSTICK_FLAG_5 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G5_A			  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_A,
		G5_B			  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_B,
		G5_X			  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_X,
		G5_Y			  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_Y,
		G5_LEFT_BUMPER	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G5_RIGHT_BUMPER	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G5_BACK			  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_BACK,
		G5_START		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_START,
		G5_GUIDE		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_GUIDE,
		G5_LEFT_THUMB	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_LEFT_THUMB,
		G5_RIGHT_THUMB	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G5_DPAD_UP		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_DPAD_UP,
		G5_DPAD_RIGHT	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G5_DPAD_DOWN	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_DPAD_DOWN,
		G5_DPAD_LEFT	  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_DPAD_LEFT,
		G5_LAST			  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_LAST,
		G5_CROSS		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_CROSS,
		G5_CIRCLE		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_CIRCLE,
		G5_SQUARE		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_SQUARE,
		G5_TRIANGLE		  = JOYSTICK_FLAG_5 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 6 Buttons */
		J6_HAT_CENTERED   = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_CENTERED,
		J6_HAT_UP         = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_UP,
		J6_HAT_RIGHT      = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_RIGHT,
		J6_HAT_DOWN       = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_DOWN,
		J6_HAT_LEFT       = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_LEFT,
		J6_HAT_RIGHT_UP   = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J6_HAT_RIGHT_DOWN = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J6_HAT_LEFT_UP    = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J6_HAT_LEFT_DOWN  = JOYSTICK_FLAG_6 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G6_A			  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_A,
		G6_B			  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_B,
		G6_X			  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_X,
		G6_Y			  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_Y,
		G6_LEFT_BUMPER	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G6_RIGHT_BUMPER	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G6_BACK			  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_BACK,
		G6_START		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_START,
		G6_GUIDE		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_GUIDE,
		G6_LEFT_THUMB	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_LEFT_THUMB,
		G6_RIGHT_THUMB	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G6_DPAD_UP		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_DPAD_UP,
		G6_DPAD_RIGHT	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G6_DPAD_DOWN	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_DPAD_DOWN,
		G6_DPAD_LEFT	  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_DPAD_LEFT,
		G6_LAST			  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_LAST,
		G6_CROSS		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_CROSS,
		G6_CIRCLE		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_CIRCLE,
		G6_SQUARE		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_SQUARE,
		G6_TRIANGLE		  = JOYSTICK_FLAG_6 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 7 Buttons */
		J7_HAT_CENTERED   = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_CENTERED,
		J7_HAT_UP         = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_UP,
		J7_HAT_RIGHT      = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_RIGHT,
		J7_HAT_DOWN       = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_DOWN,
		J7_HAT_LEFT       = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_LEFT,
		J7_HAT_RIGHT_UP   = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J7_HAT_RIGHT_DOWN = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J7_HAT_LEFT_UP    = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J7_HAT_LEFT_DOWN  = JOYSTICK_FLAG_7 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G7_A			  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_A,
		G7_B			  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_B,
		G7_X			  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_X,
		G7_Y			  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_Y,
		G7_LEFT_BUMPER	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G7_RIGHT_BUMPER	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G7_BACK			  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_BACK,
		G7_START		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_START,
		G7_GUIDE		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_GUIDE,
		G7_LEFT_THUMB	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_LEFT_THUMB,
		G7_RIGHT_THUMB	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G7_DPAD_UP		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_DPAD_UP,
		G7_DPAD_RIGHT	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G7_DPAD_DOWN	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_DPAD_DOWN,
		G7_DPAD_LEFT	  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_DPAD_LEFT,
		G7_LAST			  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_LAST,
		G7_CROSS		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_CROSS,
		G7_CIRCLE		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_CIRCLE,
		G7_SQUARE		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_SQUARE,
		G7_TRIANGLE		  = JOYSTICK_FLAG_7 | GAMEPAD_BUTTON_TRIANGLE,

		/* Joysticks / Gamepad 8 Buttons */
		J8_HAT_CENTERED   = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_CENTERED,
		J8_HAT_UP         = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_UP,
		J8_HAT_RIGHT      = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_RIGHT,
		J8_HAT_DOWN       = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_DOWN,
		J8_HAT_LEFT       = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_LEFT,
		J8_HAT_RIGHT_UP   = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_RIGHT_UP,
		J8_HAT_RIGHT_DOWN = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_RIGHT_DOWN,
		J8_HAT_LEFT_UP    = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_LEFT_UP,
		J8_HAT_LEFT_DOWN  = JOYSTICK_FLAG_8 | JOYSTICK_HAT_FLAG_LEFT_DOWN,
		G8_A			  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_A,
		G8_B			  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_B,
		G8_X			  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_X,
		G8_Y			  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_Y,
		G8_LEFT_BUMPER	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_LEFT_BUMPER,
		G8_RIGHT_BUMPER	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_RIGHT_BUMPER,
		G8_BACK			  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_BACK,
		G8_START		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_START,
		G8_GUIDE		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_GUIDE,
		G8_LEFT_THUMB	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_LEFT_THUMB,
		G8_RIGHT_THUMB	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_RIGHT_THUMB,
		G8_DPAD_UP		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_DPAD_UP,
		G8_DPAD_RIGHT	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_DPAD_RIGHT,
		G8_DPAD_DOWN	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_DPAD_DOWN,
		G8_DPAD_LEFT	  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_DPAD_LEFT,
		G8_LAST			  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_LAST,
		G8_CROSS		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_CROSS,
		G8_CIRCLE		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_CIRCLE,
		G8_SQUARE		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_SQUARE,
		G8_TRIANGLE		  = JOYSTICK_FLAG_8 | GAMEPAD_BUTTON_TRIANGLE,
	};
	ENUM_FLAGS(EInputButton)





	/* Joystick ID to Button/Axis */
	static constexpr EInputButton ToJoystickButtonFlag(EJoystickID id)
	{
		return EInputButton(u16(id) << 12);
	}
	/*TEST*/ static_assert(ToJoystickButtonFlag(EJoystickID::JOYSTICK_5) == EInputButton::JOYSTICK_FLAG_5);
	static constexpr EInputAxis ToJoystickAxisFlag(EJoystickID id)
	{
		return EInputAxis(u16(id) << 4);
	}
	/*TEST*/ static_assert(ToJoystickAxisFlag(EJoystickID::JOYSTICK_5) == EInputAxis::JOYSTICK_FLAG_5);



	/* Button/Axis to Joystick ID */
	static constexpr EJoystickID ToJoystickID(EInputButton flag)
	{
		return EJoystickID(u16(flag & EInputButton::IS_JOYSTICK_FLAG) >> 12);
	}
	/*TEST*/ static_assert(ToJoystickID(EInputButton::JOYSTICK_FLAG_7) == EJoystickID::JOYSTICK_7);
	static constexpr EJoystickID ToJoystickID(EInputAxis flag)
	{
		return EJoystickID(u16(flag & EInputAxis::IS_JOYSTICK_FLAG) >> 4);
	}
	/*TEST*/ static_assert(ToJoystickID(EInputButton::JOYSTICK_FLAG_7) == EJoystickID::JOYSTICK_7);



	/* To GLFW Key */
	static constexpr u32 ToGLFWKey(EInputButton key)
	{
		return u32(key);
	}
	/*TEST*/ static_assert(ToGLFWKey(EInputButton::KEY_D) == GLFW_KEY_D);



	/* To GLFW Mouse Button */
	static constexpr u32 ToGLFWMouseButton(EInputButton key)
	{
		return u32(key - EInputButton::MOUSE_BUTTON_OFFSET);
	}
	/*TEST*/ static_assert(ToGLFWMouseButton(EInputButton::MOUSE_BUTTON_3) == GLFW_MOUSE_BUTTON_3);



	/* To GLFW Joystick */
	static constexpr u32 ToGLFWJoystick(EJoystickID id)
	{
		ASSERT(id != EJoystickID::NONE);
		return u32(id) - 1;
	}
	/*TEST*/ static_assert(ToGLFWJoystick(EJoystickID::JOYSTICK_1) == GLFW_JOYSTICK_1);
	static constexpr u32 ToGLFWJoystick(EInputButton flag)
	{
		return ToGLFWJoystick(ToJoystickID(flag));
	}
	/*TEST*/ static_assert(ToGLFWJoystick(EInputButton::JOYSTICK_FLAG_3) == GLFW_JOYSTICK_3);
	static constexpr u32 ToGLFWJoystick(EInputAxis flag)
	{
		return ToGLFWJoystick(ToJoystickID(flag));
	}
	/*TEST*/ static_assert(ToGLFWJoystick(EInputAxis::JOYSTICK_FLAG_5) == GLFW_JOYSTICK_5);



	/* To GLFW Gamepad Button */
	static constexpr u32 ToGLFWGamepadButton(EInputButton flag)
	{
		return u32((flag & EInputButton::GAMEPAD_BUTTON_FLAGS) >> EInputButton::GAMEPAD_BUTTON_SHIFT) - 1;
	}
	/*TEST*/ static_assert(ToGLFWGamepadButton(EInputButton::G3_Y) == GLFW_GAMEPAD_BUTTON_Y);



	/* To GLFW Gamepad HAT */
	static constexpr u32 ToGLFWJoystickHat(EInputButton flag)
	{
		return u32(flag & EInputButton::IS_JOYSTICK_HAT_FLAG);
	}
	/*TEST*/ static_assert(ToGLFWJoystickHat(EInputButton::J4_HAT_RIGHT_DOWN) == GLFW_HAT_RIGHT_DOWN);



	/* To GLFW Gamepad Axis */
	static constexpr u32 ToGLFWGamepadAxis(EInputAxis flag)
	{
		return u32(flag & EInputAxis::GAMEPAD_AXIS_FLAGS) - 1;
	}
	/*TEST*/ static_assert(ToGLFWGamepadAxis(EInputAxis::G5_RIGHT_X) == GLFW_GAMEPAD_AXIS_RIGHT_X);
}